### ISSUE TITLE
CSS not working

### ISSUE THREAD

**Issue by Kyle-Jackson** [Kyle-Jackson/designportfolio#1]
Hi Thomas,
I tried updating my personal website from the coming soon page to the actual website, kylejackson.me, however the css isn't working. Everything loads fine when I use the github URL but it isn't working when I got to kylejackson.me. The errors that I'm getting are [Error] Failed to load resource: the server responded with a status of 404 (Not Found). I was wondering if you know how I can go about fixing this issue.

Thanks,
Kyle

@thomasjbradley

**Comment by thomasjbradley** [comment]
You'll have to change the `_config.yml` file so the `baseurl` is nothing, on this line here:
https://github.com/Kyle-Jackson/designportfolio/blob/gh-pages/_config.yml#L2

Change to:

```yml
baseurl: ""
```

**Comment by Kyle-Jackson** [comment]
Thanks!
